name: FistulaCheck
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.0
  firebase_analytics: ^11.3.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0
  http: ^1.2.2
  image_picker: ^1.1.2
  provider: ^6.1.5+1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/checkLogo.png"

flutter_native_splash:
  color: "#0A1B3D"
  background_image: assets/checkLogo.png
  android_12:
    image: assets/checkLogo.png
  android: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/
